name: dbt Cloud - PR Testing

on: 
  pull_request:
    branches: 
      - main

jobs:
  dbt-validate_pr:
    name: dbt PR Validation
    runs-on: ubuntu-latest

    env:
      DBT_API_KEY:             ${{ secrets.DBT_API_KEY }}
      DBT_URL:                 https://cloud.getdbt.com # no trailing backslash. Change this for single tenant deployments to your actual base url
      DBT_JOB_CAUSE:           'Github Actions PR Job' # provide a descriptive job cause here for easy debugging down the road
      DBT_ACCOUNT_ID:          7551
      DBT_PROJECT_ID:          28299
      DBT_PR_JOB_ID:           24594
      DBT_JOB_SCHEMA_OVERRIDE: PR_GITHUB_ACTIONS_${{GITHUB_EVENT_NAME}}
      DBT_JOB_BRANCH:          ${{GITHUB_HEAD_REF}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Trigger dbt job
      run: |
        python ./python/run_and_monitor_dbt_cloud_job.py